Network
manelyset/homework-4sem pull request #18
Opened 2019-04-16 14:07 UTC by manelyset

2019-06-07 13:45 UTC, yurii-litvinov requested changes
По существу всё правильно, но качество кода более уместно для первого семестра первого курса :) Надо поправить

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +type Computer (OSType:string, infected:bool, r:Random) =
Надо комментарии

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +    let mutable mInfected = infected
Можно просто infected, чтобы заменить в области видимости немутабельное имя на мутабельное. Префиксы типа m в дотнет-сообществе не очень любят (хотя сами Microsoft местами так пишут)

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +        and set newFlag = mFlag <- newFlag
Сделали б его автоматическим свойством

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +    member this.infProbability =
Методы именуются с заглавной

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +    member this.infect (otherComputer:Computer) =
И надо комментарии к каждому методу, и пустую строчку между методами, как и в C# :)

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +        if c.Infected then c.Flag <- 2
Надо пустую строчку между функциями

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +    let mutable mFlag = 1
Флаг чего? Так нельзя поля называть. И почему 1? :)

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +            if (network.[i].[j] = 1) && (computersList.[i].Flag = 2) then
Что такое 2 и не было бы лучше использовать discriminated union для представления **именованных** вариантов значения флага? :)

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/NetworkTest/NetworkTest.fs
> +type neverInfect() =
Типы в дотнете с заглавной именуются

2019-06-07 13:45 UTC, yurii-litvinov commented on 6-network/NetworkTest/NetworkTest.fs
> +let computersList1 = Array.init 4 (fun i -> Computer("Windows",false,neverInfect))
Пробелов не хватает

2019-06-08 17:16 UTC, yurii-litvinov requested changes

2019-06-08 17:16 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +type Computer (OSType:string, infected:bool, r:Random) =
Напоминаю

2019-06-08 17:16 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +        and set newFlag = mFlag <- newFlag
member val Flag = CanNotInfect with get, set

И надо его переименовать, flag не годится

2019-06-08 17:16 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +        and set infection = infected <- infection
Надо пустые строки между свойствами

2019-06-08 17:16 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +        if c.Infected then c.Flag <- CanInfect
И между функциями

2019-06-08 22:20 UTC, yurii-litvinov approved these changes

2019-06-08 22:20 UTC, yurii-litvinov commented on 6-network/Network/Program.fs
> +type Computer (OSType:string, infected:bool, r:Random) =
В реальной жизни если тимлид сказал два раза написать комментарии к классу, Вы два раза сабмитите код на ревью и два раза комментариев, которые Вам сказали написать, нету --- это увольнение за несоответствие занимаемой должности. У нас тут хиппи-пацифизм, мы типа учимся и всё такое. Зачтена.

2019-06-09 13:26 UTC, manelyset commented on 6-network/Network/Program.fs
> +type Computer (OSType:string, infected:bool, r:Random) =
А, к самому классу тоже надо было? Я думала, что только ко всем методам.

2019-10-23 23:59 UTC, merged